new pynos call to enable/disable fabric neighbor on a interface
brocade/pynos pull request #27
Opened 2016-11-17 11:13 UTC by uday83

Leaf1-2# show run int t 1/0/15
interface TenGigabitEthernet 1/0/15
 channel-group 200 mode on type standard
 no fabric isl enable
 no fabric trunk enable
 fabric neighbor-discovery disable
 no shutdown

to disable/enable  fabric neighbor-discovery disable on a interface

2016-11-17 17:45 UTC, samirsss requested changes

2016-11-17 17:45 UTC, samirsss commented on pynos/versions/base/interface.py
> +        int_types = [
is this not supported on gigabitethernet?

2016-11-18 05:55 UTC, uday83 commented on pynos/versions/base/interface.py
> +        int_types = [
fabric commands on 1G are not supported. VCS formation happens only on links with 10G and above speeds .

2016-11-18 16:56 UTC, samirsss commented
Feel free to merge this.

2016-11-18 16:56 UTC, samirsss approved these changes

2016-11-21 20:45 UTC, samirsss commented
I am going to merge this for you since I need to rev up the version of pynos today.

2016-11-21 20:46 UTC, merged